import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    
    <div className={styles.container}>
      <style jsx>
      {`
      .myspan{
        color:blue;
      }
      `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
      <span className="myspan">Hunting coders</span> </h1>
      <div className={styles.imagewrap}>
      <Image className={styles.myimg} src="/photo-4.jfif" alt="Image is loading" width={257} height={187}/>
</div>
        <p className={styles.description}>
          A blog for coders
        </p>

<div className="blogs">
  <h2>Popular Blogs</h2>
  <div className="blogItem">
    <h3>How to learn javascript in 2022</h3>
    <p>Javascript is the language used to design for logic in wev </p>
    </div>
    <div className="blogItem">
    <h3>How to learn javascript in 2022</h3>
    <p>Javascript is the language used to design for logic in wev </p>
    </div>
    <div className="blogItem">
    <h3>How to learn javascript in 2022</h3>
    <p>Javascript is the language used to design for logic in wev </p>
    </div>
    </div>
        
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
